---
title: "Study 1 - Masculine Capital Scale"
author: "Timothy J. Luke & Pär Stern"
date: "December 11, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(lme4)
library(lmerTest)

mcs <- read_csv("MCS_raw.csv")

mcs_long <- mcs %>% 
  gather(key = "key", value = "capital", names(mcs[7:78])) %>% 
  extract(key, c("story", "masculinity", "rating_type"), "(.*)_(.*)_(.*)") %>% 
  filter(!is.na(capital)) %>% 
  mutate(
    rating_type = case_when(
      rating_type == 1 ~ "personal",
      rating_type == 2 ~ "peer",
      rating_type == 3 ~ "society"
    )
  )

mcs_personal <- mcs_long %>% 
  filter(rating_type == "personal")

mcs_peer <- mcs_long %>% 
  filter(rating_type == "peer")

mcs_society <- mcs_long %>% 
  filter(rating_type == "society")

```

## Sample information

```{r}
mcs %>%
  summarise(
    Male = sum(gender == "Male"),
    Female = sum(gender == "Female"),
    "Mean Age" = round(mean(age, na.rm = TRUE), 2),
    "SD Age" = round(sd(age, na.rm = TRUE), 2),
    "Median Age" = round(median(age, na.rm = TRUE), 2)
  ) %>% 
  knitr::kable()
```


## Visualizations and descriptives

### Peer ratings

```{r descriptives}
peer_desc <- mcs_peer %>%
  group_by(masculinity) %>% 
  summarise(
    mean = mean(capital, na.rm = TRUE),
    sd = sd(capital, na.rm = TRUE),
    median = median(capital, na.rm = TRUE)
  )

knitr::kable(peer_desc)
```

```{r hist}

ggplot(mcs_peer,
       aes(
         x = capital
       )) +
  facet_wrap(~ masculinity) +
  geom_histogram(
    binwidth = 1
  ) +
  geom_vline(data = peer_desc,
             aes(
               xintercept = mean
             )) +
  geom_vline(
    xintercept = 5,
    linetype = "dashed"
  ) +
  theme_classic()

```

```{r hist gender 1}

peer_desc_gender <- mcs_peer %>%
  group_by(masculinity, gender) %>% 
  summarise(
    mean = mean(capital, na.rm = TRUE),
    sd = sd(capital, na.rm = TRUE),
    median = median(capital, na.rm = TRUE)
  )

ggplot(mcs_peer,
       aes(
         x = capital
       )) +
  facet_grid(gender ~ masculinity) +
  geom_histogram(
    binwidth = 1
  ) +
  geom_vline(data = peer_desc_gender,
             aes(
               xintercept = mean
             )) +
  geom_vline(
    xintercept = 5,
    linetype = "dashed"
  ) +
  theme_classic()

```

### Personal ratings

```{r descriptives 2}
personal_desc <- mcs_personal %>%
  group_by(masculinity) %>% 
  summarise(
    mean = mean(capital, na.rm = TRUE),
    sd = sd(capital, na.rm = TRUE),
    median = median(capital, na.rm = TRUE)
  )

knitr::kable(personal_desc)
```

```{r hist 2}

ggplot(mcs_personal,
       aes(
         x = capital
       )) +
  facet_wrap(~ masculinity) +
  geom_histogram(
    binwidth = 1
  ) +
  geom_vline(data = personal_desc,
             aes(
               xintercept = mean
             )) +
  geom_vline(
    xintercept = 5,
    linetype = "dashed"
  ) +
  theme_classic()

```

```{r hist gender 2}

personal_desc_gender <- mcs_personal %>%
  group_by(masculinity, gender) %>% 
  summarise(
    mean = mean(capital, na.rm = TRUE),
    sd = sd(capital, na.rm = TRUE),
    median = median(capital, na.rm = TRUE)
  )

ggplot(mcs_personal,
       aes(
         x = capital
       )) +
  facet_grid(gender ~ masculinity) +
  geom_histogram(
    binwidth = 1
  ) +
  geom_vline(data = personal_desc_gender,
             aes(
               xintercept = mean
             )) +
  geom_vline(
    xintercept = 5,
    linetype = "dashed"
  ) +
  theme_classic()

```

### Society ratings

```{r descriptives 3}
society_desc <- mcs_society %>%
  group_by(masculinity) %>% 
  summarise(
    mean = mean(capital, na.rm = TRUE),
    sd = sd(capital, na.rm = TRUE),
    median = median(capital, na.rm = TRUE)
  )

knitr::kable(society_desc)
```

```{r hist 3}

ggplot(mcs_society,
       aes(
         x = capital
       )) +
  facet_wrap(~ masculinity) +
  geom_histogram(
    binwidth = 1
  ) +
  geom_vline(data = society_desc,
             aes(
               xintercept = mean
             )) +
  geom_vline(
    xintercept = 5,
    linetype = "dashed"
  ) +
  theme_classic()

```

```{r hist gender 3}

society_desc_gender <- mcs_society %>%
  group_by(masculinity, gender) %>% 
  summarise(
    mean = mean(capital, na.rm = TRUE),
    sd = sd(capital, na.rm = TRUE),
    median = median(capital, na.rm = TRUE)
  )

ggplot(mcs_society,
       aes(
         x = capital
       )) +
  facet_grid(gender ~ masculinity) +
  geom_histogram(
    binwidth = 1
  ) +
  geom_vline(data = society_desc_gender,
             aes(
               xintercept = mean
             )) +
  geom_vline(
    xintercept = 5,
    linetype = "dashed"
  ) +
  theme_classic()

```

## Hypothesis test

```{r mlm 1}

mcs_peer$masculinity <- factor(mcs_peer$masculinity, levels = c("Neutral", "Masculine", "Non-masculine"))

peer_model <- lmer(capital ~ masculinity + (1|ID) + (1|story), data = mcs_peer)

summary(peer_model)

```

## Exploratory models

### Personal ratings

```{r mlm 2}

mcs_personal$masculinity <- factor(mcs_personal$masculinity, levels = c("Neutral", "Masculine", "Non-masculine"))

personal_model <- lmer(capital ~ masculinity + (1|ID) + (1|story), data = mcs_personal)

summary(personal_model)

```

### Society ratings

```{r mlm 3}

mcs_society$masculinity <- factor(mcs_society$masculinity, levels = c("Neutral", "Masculine", "Non-masculine"))

society_model <- lmer(capital ~ masculinity + (1|ID) + (1|story), data = mcs_society)

summary(society_model)

```